config/routes.rb
Rails.application.routes.draw do
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root                     to: 'tasks#index'
  get    'tasks/new',      to: 'tasks#new'
  get    'tasks/:id/edit', to: 'tasks#edit',    as: :edit
  get    'tasks/:id',      to: 'tasks#show',    as: :task
  post   'tasks/',         to: 'tasks#create'
  patch  'tasks/:id',      to: 'tasks#update'
  delete 'tasks/:id',      to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def edit() end

  def show() end

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(new_task)
    @task.save

    redirect_to root_path
  end

  def update
    @task.update(update_task)

    redirect_to root_path
  end

  def destroy
    @task.destroy

    redirect_to root_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def new_task
    params.require(:task).permit(:title, :details)
  end

  def update_task
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>My Tasks Manager</h1>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>
  <div>
    <input type="checkbox" id="scales" name="scales"
           checked>
    <label for="task"><%= link_to task.title,  task_path(task) %></label>
    <%= link_to 'delete', destroy_path(task), method: :delete %>
  </div>
<% end %>

<div>
<%= link_to 'create a task', tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<h4><%= @task.details %></h4>
<div>
    <input type="checkbox" id="scales" name="scales"
           checked>
    <label for="task"><%= "Done or not?" %></label>
</div>
<div><%= link_to 'Back to list', '/' %></div>
<div><%= link_to 'update infos', edit_path %></div>